apiVersion: apps/v1
kind: Deployment
metadata:
  name: podset-cluster-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: podset-cluster-operator
  template:
    metadata:
      labels:
        name: podset-cluster-operator
    spec:
      serviceAccountName: podset-cluster-operator
      containers:
        - name: podset-cluster-operator
          # Replace this with the built image name
          image: quay.io/xcoulon/podset-cluster-operator
          command:
          - podset-cluster-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "podset-cluster-operator"
